adjective = input("please enter an adjective: ")
noun = input("please enter a noun: ")
verb = input("please enter a verb ending in -ed: ")
print("your MadLib:")
print("the", adjective, noun, verb, "over the lazy brown dog")             
